spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/vybe_db
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

two-factor-auth:
  account-sid: AC05c1b101a257d7fc4771a566469415ab
  auth-token: 0c87a007fe9fb73db79e8cbee4aec72b
  service-id: VA514853402f129ba2a86b9a23c5ba0e2f
  channel: sms

soundtrackyourbrand:
  api:
    url: https://api.soundtrackyourbrand.com/v2

iyzico:
  apiKey:
  privateKey:
  baseUrl:

server:
  error:
    include-message: always