spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/vybe_db
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

two-factor-auth:
  account-sid:
  auth-token:
  service-id:
  channel: sms

soundtrackyourbrand:
  api:
    url: https://api.soundtrackyourbrand.com/v2

iyzico:
  apiKey:
  privateKey:
  baseUrl:

server:
  error:
    include-message: always
