spring:
  datasource:
    password:
    url:
    username:
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: create-drop
two-factor-auth:
  account-sid:
  auth-token:
  service-id:
  channel: