spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/vybe_db
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop